CREATE TABLE IF NOT EXISTS common.UserSessions
(
  Id         TEXT PRIMARY KEY,
  UserId     INTEGER   NOT NULL REFERENCES common.Users (Id) ON DELETE CASCADE,
  CreatedDate TIMESTAMP NOT NULL DEFAULT NOW(),
  ExpiryDate TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '30 day'
);
