CREATE TABLE IF NOT EXISTS UserSessions (
    Id         TEXT PRIMARY KEY,
    UserId     INTEGER NOT NULL REFERENCES Users (Id),
    CreateDate TIMESTAMP NOT NULL DEFAULT NOW(),
    ExpiryDate TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '1 day'
);
